### ISSUE TITLE
Stuck in `python -m textual`

### ISSUE THREAD

**Issue by davidgasquez** [Textualize/textual-serve#3]
I was trying to deploy a HF app with `textual-serve` and they seem to get stuck on the initial screen.

https://huggingface.co/spaces/davidgasquez/harlequin-web

You can see [all the files here](https://huggingface.co/spaces/davidgasquez/harlequin-web/tree/main).

Not sure what is going on there and I have no rush. Just wanted to play around.

**Comment by bswck** [comment]
Same issue happens in Textual docs, actually.
After some time the screen says "session ended".
What should happen is us knowing the issue from looking in the devtools console, but you should have some info in your logs. Anything there?

**Comment by davidgasquez** [comment]
Not sure there is anything in the devtools console. That said, I don't know enough about front-end to make an absolute call.

**Comment by bswck** [comment]
> Not sure there is anything in the devtools console. That said, I don't know enough about front-end to make an absolute call.

Yes, that's what *should* happen, but doesn't.
